# Generated by Django 4.2.11 on 2024-12-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kunder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kund_nummer", models.IntegerField()),
                ("namn", models.CharField(max_length=64)),
            ],
        ),
    ]
